// <auto-generated />
namespace QATool.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class compositeKeyStep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(compositeKeyStep));
        
        string IMigrationMetadata.Id
        {
            get { return "201301151541537_compositeKeyStep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
